# Generated by Django 2.0.7 on 2018-07-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180726_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
