# Generated by Django 2.0.7 on 2018-07-27 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 27, 21, 57, 24, 851574)),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='ip',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='session',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
