# Generated by Django 2.0.7 on 2018-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180727_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogview',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
