# Generated by Django 2.0.7 on 2018-07-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180727_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogview',
            old_name='question',
            new_name='blog',
        ),
    ]
