# Generated by Django 2.0.7 on 2018-07-29 08:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180729_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
