# Generated by Django 2.0.7 on 2018-07-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180729_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='code_description',
            field=models.TextField(blank=True, default='No description provided.', max_length=1000, null=True),
        ),
    ]
