# Generated by Django 2.0.7 on 2018-07-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20180712_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/media/profile_pic', upload_to=''),
        ),
    ]
