# Generated by Django 2.0.7 on 2018-07-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20180712_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='user-icon.png', upload_to=''),
        ),
    ]
