# Generated by Django 2.0.7 on 2018-07-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_followuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followuser',
            old_name='user',
            new_name='following',
        ),
        migrations.RenameField(
            model_name='followuser',
            old_name='follow',
            new_name='is_following',
        ),
    ]
