# Generated by Django 2.0.7 on 2018-07-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20180715_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuser',
            name='followed_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='userprofile.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followuser',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='userprofile.Profile'),
        ),
    ]
