# Generated by Django 2.0.7 on 2018-07-23 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0009_auto_20180716_0737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followuser',
            unique_together={('following', 'followed_by')},
        ),
    ]
